package converter;

import java.io.File;
import java.io.IOException;

public class CSVConverter {
    /**
    * Function used only for validation of the challenge solution.
    * @param args Not used.
    * @throws IOException If there is a problem reading the input files or
    * write the output files.
    */
    public static void main(String[] args) throws IOException {
        File inputsFolder = new File("./inputs/");
        File outputsFolder = new File("./outputs/");
        new CSVConverter().convertFolder(inputsFolder, outputsFolder);
    }

    /**
    * Converts all CSV files from the inputs folder. The results are generated
    * in the outputs folder, leaving the original files unchanged.
    *
    * @param inputsFolder Folder containing the CSV files generated by the web page.
    * @param outputsFolder Folder where the files generated in the format will be placed
    * required by the subsystem.
    *
    * @throws IOException If there is a problem reading the input files or
    * write the output files.
    */
    public void convertFolder(File inputsFolder, File outputsFolder) throws IOException {
    }
}
